version: "3.7"
services:
    cli:
        build:
            context: ./docker/cli
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
        ports:
            - '3306:3306'
        volumes:
            - db:/var/lib/mysql

volumes:
    db:
